#!/bin/sh -e

SCRIPT_DIR=`readlink -f $(dirname $0)`
BUILD_DIR=$SCRIPT_DIR/build

APP_NAME=dbcat

cd $SCRIPT_DIR
VERSION=`cat $SCRIPT_DIR/version``test -f $SCRIPT_DIR/build_num && (echo -n '-';cat $SCRIPT_DIR/build_num) || echo -n`
VERSION=`echo $VERSION | sed 's/ *$//'`
echo Build $VERSION

DEB_NAME=${APP_NAME}_${VERSION}_all.deb
echo $DEB_NAME

echo Cleaning
rm -rf $BUILD_DIR
rm -f *.deb

echo Create pkg structure
mkdir -p $BUILD_DIR/usr/share/$APP_NAME
mkdir -p $BUILD_DIR/usr/share/doc/$APP_NAME

echo Copying files
cp -r $SCRIPT_DIR/debian $BUILD_DIR/DEBIAN
cp -r $SCRIPT_DIR/etc $BUILD_DIR/
cp -r $SCRIPT_DIR/usr $BUILD_DIR/
cp -r $SCRIPT_DIR/dbcat $BUILD_DIR/usr/share/$APP_NAME/
cp -r $SCRIPT_DIR/frontend $BUILD_DIR/usr/share/$APP_NAME/
cp -r $SCRIPT_DIR/manage.py $BUILD_DIR/usr/share/$APP_NAME/

mv $BUILD_DIR/DEBIAN/changelog $BUILD_DIR/usr/share/doc/$APP_NAME/changelog.Debian
gzip -9 $BUILD_DIR/usr/share/doc/$APP_NAME/changelog.Debian
mv $BUILD_DIR/DEBIAN/copyright $BUILD_DIR/usr/share/doc/$APP_NAME/
sed -i 's/#VERSION#/'$VERSION'/g' $BUILD_DIR/DEBIAN/control
find $BUILD_DIR/usr -name __pycache__ -prune -exec rm -rf {} \;
find $BUILD_DIR/usr -name \*.pyc -prune -exec rm -rf {} \;

echo Chmod
chmod 755 $(find $BUILD_DIR/DEBIAN -type d)
chmod 644 $BUILD_DIR/DEBIAN/control
chmod 644 $BUILD_DIR/DEBIAN/conffiles
chmod -f 755 $BUILD_DIR/DEBIAN/preinst || echo "No preinst script"
chmod -f 755 $BUILD_DIR/DEBIAN/postinst || echo "No postinst script"
chmod -f 755 $BUILD_DIR/DEBIAN/prerm || echo "No prerm script"
chmod -f 755 $BUILD_DIR/DEBIAN/postrm || echo "No postrm script"

chmod 755 $(find $BUILD_DIR/etc -type d)
chmod 644 $(find $BUILD_DIR/etc -type f)
chmod 755 $(find $BUILD_DIR/etc/init.d -type f)

chmod 755 $(find $BUILD_DIR/usr -type d)
chmod 644 $(find $BUILD_DIR/usr -type f)

for bin_dir in `find $BUILD_DIR/usr/ -name bin -type d`
do
    chmod 755 $(find $bin_dir -type f)
done

echo Gzip man pages
gzip -9 $BUILD_DIR/usr/share/man/man1/*

echo Building deb
fakeroot dpkg-deb --build $BUILD_DIR
mv build.deb $DEB_NAME

echo Lintinan
lintian $DEB_NAME

echo Done



