#!/bin/sh -e


git checkout master

old_version=`cat version`
new_version=`echo $old_version | awk -v FS='.' -v OFS='.' '{$(NF) = $(NF) + 1; print $0}'`

git flow hotfix start $new_version
echo $new_version | cat > version
echo '1' | cat > build_num
git add version
git commit -m 'Version switched '$old_version' -> '$new_version' for hotfix' version

