#!/bin/sh

SCRIPT_DIR=`readlink -f $(dirname $0)`
BUILD_DIR=$SCRIPT_DIR/build

APP_NAME=dbcat

cd $SCRIPT_DIR
VERSION=`cat $SCRIPT_DIR/version``test -f $SCRIPT_DIR/build_num && (echo -n '-';cat $SCRIPT_DIR/build_num) || echo -n`
VERSION=`echo $VERSION | sed 's/ *$//'`
echo Build $VERSION

DEB_NAME=${APP_NAME}_${VERSION}_all.deb
echo $DEB_NAME